# Generated by Django 3.2 on 2021-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('dni', models.IntegerField(unique=True, verbose_name='dni')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_GOLD', models.BooleanField(default=False)),
                ('_is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('_is_superuser', models.BooleanField(default=False)),
                ('tipo_de_usuario', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
            ],
            options={
                'permissions': (('es_chofer', 'Es un chofer'),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.account',),
        ),
    ]
