# Generated by Django 3.2 on 2021-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='dni'),
        ),
    ]
