# Generated by Django 3.2 on 2021-05-27 03:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_chofer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chofer',
        ),
        migrations.AlterField(
            model_name='account',
            name='dni',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='dni'),
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
