# Generated by Django 3.2 on 2021-05-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210527_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tipo_de_usuario',
        ),
        migrations.AddField(
            model_name='chofer',
            name='is_chofer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
