# Generated by Django 3.2 on 2021-05-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210512_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='_is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='_is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
