# Generated by Django 3.2 on 2021-05-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210512_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tipo_de_usuario',
            field=models.BooleanField(default=0),
        ),
    ]
