# Generated by Django 3.2 on 2021-06-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chofer_is_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reactivar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
