# Generated by Django 3.2 on 2021-06-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210527_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.BigIntegerField()),
                ('nombre_titular', models.CharField(max_length=40)),
            ],
        ),
    ]
