# Generated by Django 3.2 on 2021-05-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0007_viaje_estado'),
        ('users', '0005_account_tipo_de_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.account')),
                ('contacto', models.IntegerField()),
                ('combi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Combi19App.vehiculo')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.account',),
        ),
    ]
