# Generated by Django 3.2 on 2021-05-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0007_viaje_estado'),
        ('users', '0006_chofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='combi',
            field=models.OneToOneField(choices=[('AC 201 WX', 'AC 201 WX')], on_delete=django.db.models.deletion.PROTECT, to='Combi19App.vehiculo'),
        ),
    ]
