# Generated by Django 3.2 on 2021-06-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210602_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
    ]
