# Generated by Django 3.2.2 on 2021-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
