# Generated by Django 3.2.2 on 2021-05-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('provincia', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('km', models.IntegerField()),
                ('destino', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='Combi19App.lugar')),
                ('origen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='Combi19App.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.IntegerField()),
                ('modelo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('combi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.vehiculo')),
                ('ruta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.ruta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('fecha', 'combi'), name='viaje_unico'),
        ),
    ]
