# Generated by Django 3.2.2 on 2021-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
