# Generated by Django 3.2 on 2021-06-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='asientos_ocupados',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
