# Generated by Django 3.2 on 2021-05-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0002_insumo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.ruta'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(choices=[('La Plata', 'La Plata'), ('Neuquen', 'Neuquen')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(choices=[('La Plata', 'La Plata'), ('Neuquen', 'Neuquen')], max_length=15),
        ),
    ]
