# Generated by Django 3.2 on 2021-05-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210527_0129'),
        ('Combi19App', '0002_insumo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='chofer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.chofer'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('origen', 'destino')},
        ),
    ]
