# Generated by Django 3.2 on 2021-06-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0002_viaje_asientos_ocupados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='asientos_ocupados',
            new_name='asientos_disponibles',
        ),
    ]
