# Generated by Django 3.2 on 2021-06-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0003_rename_asientos_ocupados_viaje_asientos_disponibles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='asientos_disponibles',
            new_name='asientos_ocupados',
        ),
    ]
