# Generated by Django 3.2.2 on 2021-05-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0003_auto_20210508_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='combi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.vehiculo'),
        ),
    ]
