# Generated by Django 3.2 on 2021-05-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0003_auto_20210508_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.AddField(
            model_name='viaje',
            name='combi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.vehiculo'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_y_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
