# Generated by Django 3.2 on 2021-05-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0004_auto_20210509_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='fecha_y_hora',
            new_name='fecha',
        ),
    ]
