# Generated by Django 3.2.2 on 2021-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        ('Combi19App', '0004_rename_asientos_disponibles_viaje_asientos_ocupados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='insumo',
            field=models.ManyToManyField(blank=True, default=None, to='tienda.Insumo'),
        ),
    ]
