# Generated by Django 3.2 on 2021-05-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0004_auto_20210528_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='provincia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
