# Generated by Django 3.2.2 on 2021-05-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0004_viaje_combi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='combi',
            field=models.CharField(choices=[('AC 201 WX', 'AC 201 WX')], max_length=15),
        ),
    ]
