# Generated by Django 3.2.2 on 2021-06-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0005_auto_20210609_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de ruta'),
        ),
    ]
