# Generated by Django 3.2.2 on 2021-05-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0005_alter_viaje_combi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='combi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.vehiculo'),
        ),
    ]
