# Generated by Django 3.2 on 2021-05-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0005_rename_fecha_y_hora_viaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
