# Generated by Django 3.2 on 2021-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0005_auto_20210528_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='provincia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
