# Generated by Django 3.2.2 on 2021-05-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0006_alter_viaje_combi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='combi',
        ),
    ]
