# Generated by Django 3.2 on 2021-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0006_auto_20210528_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Lugar'),
        ),
    ]
