# Generated by Django 3.2 on 2021-05-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('Combi19App', '0007_viaje_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Lugares'},
        ),
        migrations.AddField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.chofer'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='insumo',
            field=models.ManyToManyField(blank=True, to='Combi19App.Insumo'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('fecha', 'combi', 'chofer'), name='viaje_unico'),
        ),
    ]
