# Generated by Django 3.2 on 2021-06-21 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0008_pasaje_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='km',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
