# Generated by Django 3.2 on 2021-05-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_chofer_options'),
        ('Combi19App', '0008_auto_20210512_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.chofer'),
        ),
    ]
