# Generated by Django 3.2 on 2021-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0009_alter_viaje_chofer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viaje',
            name='viaje_unico',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='insumo',
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('fecha', 'combi'), name='viaje_unico'),
        ),
    ]
