# Generated by Django 3.2 on 2021-06-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0010_alter_comentario_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='ruta',
            name='comentarios',
            field=models.ManyToManyField(blank=True, default=None, to='Combi19App.Comentario'),
        ),
    ]
