# Generated by Django 3.2 on 2021-06-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0011_auto_20210622_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='ruta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.ruta'),
        ),
    ]
