# Generated by Django 3.2.2 on 2021-06-26 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Combi19App', '0012_auto_20210622_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('dolor_cabeza', models.BooleanField(blank=True, null=True)),
                ('dolor_garganta', models.BooleanField(blank=True, null=True)),
                ('dolor_muscular', models.BooleanField(blank=True, null=True)),
                ('vomitos_diarrea', models.BooleanField(blank=True, null=True)),
                ('perdida_gusto_olfato', models.BooleanField(blank=True, null=True)),
                ('tos', models.BooleanField(blank=True, null=True)),
                ('dificultad_respiratoria', models.BooleanField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Testeos',
            },
        ),
    ]
