# Generated by Django 3.2 on 2021-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0015_alter_testeo_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='testeo',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
