# Generated by Django 3.2 on 2021-06-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0016_testeo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='testeo',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Combi19App.viaje'),
        ),
    ]
