# Generated by Django 3.2 on 2021-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0018_auto_20210627_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
