# Generated by Django 3.2 on 2021-06-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0020_alter_viaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estado2',
            field=models.CharField(choices=[('cancelado', 'CANCELADO'), ('finalizado', 'FINALIZADO'), ('comenzado', 'COMENZADO')], default=('comenzado', 'COMENZADO'), max_length=12),
        ),
    ]
