# Generated by Django 3.2 on 2021-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0021_viaje_estado2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='cancelado',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='estado',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado2',
            field=models.CharField(choices=[(0, 'COMENZADO'), (1, 'FINALIZADO'), (2, 'CANCELADO')], default=(2, 'CANCELADO'), max_length=12),
        ),
    ]
