# Generated by Django 3.2 on 2021-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0022_auto_20210627_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado2',
            field=models.CharField(choices=[(0, 'COMENZADO'), (1, 'FINALIZADO'), (2, 'CANCELADO')], default=(0, 'COMENZADO'), max_length=12),
        ),
    ]
