# Generated by Django 3.2 on 2021-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0023_alter_viaje_estado2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado2',
            field=models.CharField(choices=[('com', 'COMENZADO'), ('fin', 'FINALIZADO'), ('can', 'CANCELADO')], default=('com', 'COMENZADO'), max_length=3),
        ),
    ]
