# Generated by Django 3.2 on 2021-06-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0024_alter_viaje_estado2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='estado2',
            new_name='estado',
        ),
    ]
