# Generated by Django 3.2 on 2021-06-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combi19App', '0025_rename_estado2_viaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='estado',
            field=models.CharField(choices=[('pen', 'PENDIENTE'), ('fin', 'FINALIZADO'), ('can', 'CANCELADO')], default=('pen', 'PENDIENTE'), max_length=3),
        ),
    ]
